// Copyright (c) 2026 Osman Alperen Çinar-Koraş (oakisnotree). Licensed under AGPL-3.0.

pub mod config;
pub mod crypto;
pub mod db;
pub mod util;

pub mod domain;
// pub mod data;
pub mod server;
pub mod workspace_config;
// pub mod wire;

pub mod engine;
pub mod services;
pub mod signal;

pub mod api;
pub mod cli;
pub mod docker;
pub mod hub;
pub mod sdk;
pub mod sync;

#[cfg(feature = "flutter")]
pub mod bridge;
#[cfg(feature = "flutter")]
mod frb_generated; /* auto-generated by flutter_rust_bridge_codegen */

pub use sdk::DspatchSdk;
