CREATE TABLE IF NOT EXISTS agent_providers (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_path TEXT,
    git_url TEXT,
    git_branch TEXT,
    entry_point TEXT NOT NULL,
    description TEXT,
    readme TEXT,
    required_env_json TEXT NOT NULL DEFAULT '[]',
    required_mounts_json TEXT NOT NULL DEFAULT '[]',
    fields_json TEXT NOT NULL DEFAULT '{}',
    hub_slug TEXT,
    hub_author TEXT,
    hub_category TEXT,
    hub_tags_json TEXT NOT NULL DEFAULT '[]',
    hub_version INTEGER,
    hub_repo_url TEXT,
    hub_commit_hash TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);